package onfido

const (
	//report names
	DOCUMENT_REPORT = "document"
	SELFIE_REPORT   = "facial_similarity_photo"

	// country of residence
	INDIA = "IND"

	// newrelic metric constants
	ONFIDO_CREATE_APPLICANT_CALL  = "ONFIDO_CREATE_APPLICANT_CALL"
	ONFIDO_UPLOAD_DOCUMENT_CALL   = "ONFIDO_UPLOAD_DOCUMENT_CALL"
	ONFIDO_CREATE_CHECK_CALL      = "ONFIDO_CREATE_CHECK_CALL"
	ONFIDO_RETRIVE_REPORT_CALL    = "ONFIDO_RETRIVE_REPORT_CALL"
	ONFIDO_DOWNLOAD_DOCUMENT_CALL = "ONFIDO_DOWNLOAD_DOCUMENT_CALL"
)
