// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	deposit "bitbucket.org/junglee_games/getsetgo/sdks/deposit"
	mock "github.com/stretchr/testify/mock"
)

// Deposit is an autogenerated mock type for the Deposit type
type Deposit struct {
	mock.Mock
}

// GetFirstDepositFromHouzat provides a mock function with given fields: mobile
func (_m *Deposit) GetFirstDepositFromHouzat(mobile string) (*deposit.DepositResponse, error) {
	ret := _m.Called(mobile)

	var r0 *deposit.DepositResponse
	if rf, ok := ret.Get(0).(func(string) *deposit.DepositResponse); ok {
		r0 = rf(mobile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deposit.DepositResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(mobile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDeposit interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeposit creates a new instance of Deposit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeposit(t mockConstructorTestingTNewDeposit) *Deposit {
	mock := &Deposit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
