// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DigilockerConfig is an autogenerated mock type for the DigilockerConfig type
type DigilockerConfig struct {
	mock.Mock
}

// GetDigilockerAppId provides a mock function with given fields:
func (_m *DigilockerConfig) GetDigilockerAppId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDigilockerAppKey provides a mock function with given fields:
func (_m *DigilockerConfig) GetDigilockerAppKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDigilockerEndpoint provides a mock function with given fields:
func (_m *DigilockerConfig) GetDigilockerEndpoint() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewDigilockerConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewDigilockerConfig creates a new instance of DigilockerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDigilockerConfig(t mockConstructorTestingTNewDigilockerConfig) *DigilockerConfig {
	mock := &DigilockerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
